stores_list = [
  { title: 'A10 Center', city: 'Wildau', street: 'Wildau street', spaces_count: 660 },
  { title: 'HACO Center', city: 'Wadern', street: 'Wadern street', spaces_count: 110 },
  { title: 'Hirsch Center', city: 'Aachen', street: 'Aachen street', spaces_count: 151 },
  { title: 'Q6Q7', city: 'Mannheim', street: 'Mannheim street', spaces_count: 186 },
  { title: 'Stadthöfe', city: 'Hamburg', street: 'Hamburg street', spaces_count: 180 },
  { title: 'Castle terraces', city: 'Homburg', street: 'Homburg street', spaces_count: 165 },
  { title: 'Elisengalerie', city: 'Aachen', street: 'Aachen street', spaces_count: 125 },
  { title: 'City Center Porz', city: 'Cologne-Porz', street: 'Cologne-Porz street', spaces_count: 80 },
  { title: 'Gallery Wiener Platz', city: 'Cologne', street: 'Cologne street', spaces_count: 90 },
  { title: 'Barkhof Passage', city: 'Hamburg', street: 'Hamburg street', spaces_count: 660 },
  { title: 'Kuhn Center', city: 'Linden', street: 'Linden street', spaces_count: 330 },
  { title: 'Marktkauf Center', city: 'Hamburg-Bergedorf', street: 'Hamburg-Bergedorf street', spaces_count: 112 },
  { title: 'Marketplace Gallery', city: 'Hamburg-Bramfeld', street: 'Hamburg-Bramfeld street', spaces_count: 195 },
  { title: 'Nedderfeld Center', city: 'Hamburg-Eppendorf', street: 'Hamburg-Eppendorf street', spaces_count: 170 },
  { title: 'Shopping meeting point Farmsen', city: 'Hamburg-Farmsen', street: 'Hamburg-Farmsen street', spaces_count: 219 },
  { title: 'Luna Center', city: 'Hamburg-Wilhelmsburg', street: 'Hamburg-Wilhelmsburg street', spaces_count: 83 },
  { title: 'Lurup Center', city: 'Hamburg-Lurup', street: 'Hamburg-Lurup street', spaces_count: 158 },
  { title: 'Market purchase center', city: 'Hamburg-Harburg', street: 'Hamburg-Harburg street', spaces_count: 185 },
  { title: 'Süderelbe shopping center', city: 'Hamburg-Harburg', street: 'Hamburg-Harburg street', spaces_count: 80 },
  { title: 'Shopping center Langenhorner Markt', city: 'Langenhorn', street: 'Langenhorn street', spaces_count: 78 },
  { title: 'EKZ Steep Shoop', city: 'Hamburg-Steilshoop', street: 'Hamburg-Steilshoop street', spaces_count: 127 },
  { title: 'Bleichenhof Passage', city: 'Hamburg', street: 'Hamburg street', spaces_count: 36 },
  { title: 'Galleria', city: 'Hamburg', street: 'Hamburg street', spaces_count: 26 },
  { title: 'Ruppiner shopping center', city: 'Neuruppin', street: 'Neuruppin street', spaces_count: 300 },
  { title: 'Orange Park', city: 'Oranienburg', street: 'Oranienburg street', spaces_count: 8000 },
  { title: 'Forest City Center', city: 'Potsdam', street: 'Potsdam street', spaces_count: 102 },
  { title: 'Havelpark', city: 'Rathenau', street: 'Rathenau street', spaces_count: 280 },
  { title: 'City Center', city: 'Bremen', street: 'Bremen street', spaces_count: 170 },
  { title: 'Domshof Passage', city: 'Bremen', street: 'Bremen street', spaces_count: 135 }
]

spaces_list = [
  { title: 'Heller, Marquardt and Schneider', size: 600, price_per_day: 60, price_per_week: 360, price_per_month: 1380, store_id: 12 },
  { title: 'Paucek and Sons', size: 863, price_per_day: 86, price_per_week: 516, price_per_month: 1978, store_id: 5 },
  { title: 'Gaylord-Cummerata', size: 355, price_per_day: 35, price_per_week: 210, price_per_month: 805, store_id: 19 },
  { title: 'Conn-Lesch', size: 969, price_per_day: 96, price_per_week: 576, price_per_month: 2208, store_id: 6 },
  { title: 'Renner LLC', size: 933, price_per_day: 93, price_per_week: 558, price_per_month: 2139, store_id: 15 },
  { title: 'Barton, Konopelski and Crooks', size: 766, price_per_day: 76, price_per_week: 456, price_per_month: 1748, store_id: 26 },
  { title: 'Lebsack-Gislason', size: 830, price_per_day: 83, price_per_week: 498, price_per_month: 1909, store_id: 3 },
  { title: 'Haag LLC', size: 600, price_per_day: 60, price_per_week: 360, price_per_month: 1380, store_id: 6 },
  { title: 'Cormier Inc', size: 611, price_per_day: 61, price_per_week: 366, price_per_month: 1403, store_id: 20 },
  { title: 'Jerde-Thiel', size: 399, price_per_day: 39, price_per_week: 234, price_per_month: 897, store_id: 16 },
  { title: 'Zemlak-Waters', size: 135, price_per_day: 13, price_per_week: 78, price_per_month: 299, store_id: 22 },
  { title: 'Gleichner, Lemke and Hammes', size: 361, price_per_day: 36, price_per_week: 216, price_per_month: 828, store_id: 17 },
  { title: 'Kling and Sons', size: 455, price_per_day: 45, price_per_week: 270, price_per_month: 1035, store_id: 12 },
  { title: 'Bartoletti Inc', size: 427, price_per_day: 42, price_per_week: 252, price_per_month: 966, store_id: 1 },
  { title: 'Kutch and Sons', size: 267, price_per_day: 26, price_per_week: 156, price_per_month: 598, store_id: 25 },
  { title: 'Mosciski-Sporer', size: 731, price_per_day: 73, price_per_week: 438, price_per_month: 1679, store_id: 12 },
  { title: 'Stracke, Renner and Leffler', size: 592, price_per_day: 59, price_per_week: 354, price_per_month: 1357, store_id: 1 },
  { title: 'Wolff-Reynolds', size: 637, price_per_day: 63, price_per_week: 378, price_per_month: 1449, store_id: 9 },
  { title: 'Emmerich-Barton', size: 946, price_per_day: 94, price_per_week: 564, price_per_month: 2162, store_id: 16 },
  { title: 'Mosciski, McCullough and Steuber', size: 415, price_per_day: 41, price_per_week: 246, price_per_month: 943, store_id: 7 },
  { title: 'Armstrong Group', size: 604, price_per_day: 60, price_per_week: 360, price_per_month: 1380, store_id: 22 },
  { title: "O'Kon, Miller and Batz", size: 949, price_per_day: 94, price_per_week: 564, price_per_month: 2162, store_id: 17 },
  { title: 'Hegmann, Stehr and Rolfson', size: 861, price_per_day: 86, price_per_week: 516, price_per_month: 1978, store_id: 3 },
  { title: 'Tromp-Treutel', size: 908, price_per_day: 90, price_per_week: 540, price_per_month: 2070, store_id: 24 },
  { title: 'Welch-Steuber', size: 291, price_per_day: 29, price_per_week: 174, price_per_month: 667, store_id: 19 },
  { title: 'Buckridge and Sons', size: 132, price_per_day: 13, price_per_week: 78, price_per_month: 299, store_id: 18 },
  { title: 'McGlynn-Kozey', size: 717, price_per_day: 71, price_per_week: 426, price_per_month: 1633, store_id: 19 },
  { title: 'Gutkowski, Hackett and King', size: 233, price_per_day: 23, price_per_week: 138, price_per_month: 529, store_id: 16 },
  { title: 'Walsh, Nader and Donnelly', size: 628, price_per_day: 62, price_per_week: 372, price_per_month: 1426, store_id: 14 },
  { title: 'Stroman-Mitchell', size: 866, price_per_day: 86, price_per_week: 516, price_per_month: 1978, store_id: 25 },
  { title: 'Quitzon-West', size: 307, price_per_day: 30, price_per_week: 180, price_per_month: 690, store_id: 17 },
  { title: 'Lueilwitz-Roob', size: 750, price_per_day: 75, price_per_week: 450, price_per_month: 1725, store_id: 6 },
  { title: 'Koss-Green', size: 273, price_per_day: 27, price_per_week: 162, price_per_month: 621, store_id: 25 },
  { title: 'Dietrich LLC', size: 331, price_per_day: 33, price_per_week: 198, price_per_month: 759, store_id: 9 },
  { title: 'Schamberger-Lebsack', size: 490, price_per_day: 49, price_per_week: 294, price_per_month: 1127, store_id: 28 },
  { title: 'Bailey and Sons', size: 939, price_per_day: 93, price_per_week: 558, price_per_month: 2139, store_id: 17 },
  { title: 'Zulauf-Schoen', size: 235, price_per_day: 23, price_per_week: 138, price_per_month: 529, store_id: 11 },
  { title: 'Barton-Williamson', size: 450, price_per_day: 45, price_per_week: 270, price_per_month: 1035, store_id: 16 },
  { title: "O'Connell-Kihn", size: 419, price_per_day: 41, price_per_week: 246, price_per_month: 943, store_id: 5 },
  { title: 'West, Skiles and Klein', size: 206, price_per_day: 20, price_per_week: 120, price_per_month: 460, store_id: 11 },
  { title: 'Howell-Hansen', size: 786, price_per_day: 78, price_per_week: 468, price_per_month: 1794, store_id: 20 },
  { title: 'Erdman, Corwin and Feil', size: 350, price_per_day: 35, price_per_week: 210, price_per_month: 805, store_id: 24 },
  { title: 'White-Powlowski', size: 927, price_per_day: 92, price_per_week: 552, price_per_month: 2116, store_id: 12 },
  { title: 'Leuschke Inc', size: 468, price_per_day: 46, price_per_week: 276, price_per_month: 1058, store_id: 15 },
  { title: 'Mante-Kuvalis', size: 504, price_per_day: 50, price_per_week: 300, price_per_month: 1150, store_id: 5 },
  { title: 'Batz Group', size: 415, price_per_day: 41, price_per_week: 246, price_per_month: 943, store_id: 1 },
  { title: 'Gaylord, Wisoky and Collins', size: 298, price_per_day: 29, price_per_week: 174, price_per_month: 667, store_id: 9 },
  { title: 'Bashirian, Parisian and Rutherford', size: 693, price_per_day: 69, price_per_week: 414, price_per_month: 1587, store_id: 7 },
  { title: 'Quitzon-Anderson', size: 997, price_per_day: 99, price_per_week: 594, price_per_month: 2277, store_id: 15 },
  { title: 'Stark Group', size: 761, price_per_day: 76, price_per_week: 456, price_per_month: 1748, store_id: 24 },
  { title: 'Dickens, Botsford and Balistreri', size: 164, price_per_day: 16, price_per_week: 96, price_per_month: 368, store_id: 10 },
  { title: 'Considine and Sons', size: 406, price_per_day: 40, price_per_week: 240, price_per_month: 920, store_id: 5 },
  { title: 'Shanahan-Upton', size: 645, price_per_day: 64, price_per_week: 384, price_per_month: 1472, store_id: 28 },
  { title: 'Collins Group', size: 165, price_per_day: 16, price_per_week: 96, price_per_month: 368, store_id: 10 },
  { title: 'Mayert, Pollich and Pfeffer', size: 784, price_per_day: 78, price_per_week: 468, price_per_month: 1794, store_id: 12 },
  { title: 'Cruickshank-Morissette', size: 247, price_per_day: 24, price_per_week: 144, price_per_month: 552, store_id: 6 },
  { title: 'Barrows, Langosh and Conn', size: 284, price_per_day: 28, price_per_week: 168, price_per_month: 644, store_id: 11 },
  { title: 'Bernhard LLC', size: 684, price_per_day: 68, price_per_week: 408, price_per_month: 1564, store_id: 18 },
  { title: 'Smitham Inc', size: 802, price_per_day: 80, price_per_week: 480, price_per_month: 1840, store_id: 25 },
  { title: 'Altenwerth-Sporer', size: 270, price_per_day: 27, price_per_week: 162, price_per_month: 621, store_id: 28 },
  { title: 'Tillman and Sons', size: 286, price_per_day: 28, price_per_week: 168, price_per_month: 644, store_id: 14 },
  { title: 'Stiedemann-Bechtelar', size: 574, price_per_day: 57, price_per_week: 342, price_per_month: 1311, store_id: 3 },
  { title: 'Marquardt, Volkman and Mueller', size: 786, price_per_day: 78, price_per_week: 468, price_per_month: 1794, store_id: 4 },
  { title: 'Yundt, Mayer and Armstrong', size: 966, price_per_day: 96, price_per_week: 576, price_per_month: 2208, store_id: 8 },
  { title: 'Harvey-Wiza', size: 333, price_per_day: 33, price_per_week: 198, price_per_month: 759, store_id: 23 },
  { title: 'Schaefer and Sons', size: 547, price_per_day: 54, price_per_week: 324, price_per_month: 1242, store_id: 17 },
  { title: 'Satterfield, Koelpin and Kunde', size: 891, price_per_day: 89, price_per_week: 534, price_per_month: 2047, store_id: 1 },
  { title: 'Reilly, Hagenes and Wehner', size: 834, price_per_day: 83, price_per_week: 498, price_per_month: 1909, store_id: 27 },
  { title: 'Witting Group', size: 662, price_per_day: 66, price_per_week: 396, price_per_month: 1518, store_id: 14 },
  { title: 'Nader, Koelpin and Smith', size: 446, price_per_day: 44, price_per_week: 264, price_per_month: 1012, store_id: 14 },
  { title: 'Tillman Inc', size: 592, price_per_day: 59, price_per_week: 354, price_per_month: 1357, store_id: 9 },
  { title: 'Fay-Goldner', size: 290, price_per_day: 29, price_per_week: 174, price_per_month: 667, store_id: 1 },
  { title: 'Parisian and Sons', size: 558, price_per_day: 55, price_per_week: 330, price_per_month: 1265, store_id: 11 },
  { title: 'Berge, Marks and Schaefer', size: 269, price_per_day: 26, price_per_week: 156, price_per_month: 598, store_id: 1 },
  { title: 'Rowe and Sons', size: 725, price_per_day: 72, price_per_week: 432, price_per_month: 1656, store_id: 24 },
  { title: 'Hammes LLC', size: 618, price_per_day: 61, price_per_week: 366, price_per_month: 1403, store_id: 18 },
  { title: 'Witting and Sons', size: 529, price_per_day: 52, price_per_week: 312, price_per_month: 1196, store_id: 8 },
  { title: 'Bartell, Padberg and Volkman', size: 844, price_per_day: 84, price_per_week: 504, price_per_month: 1932, store_id: 5 },
  { title: 'Hansen and Sons', size: 654, price_per_day: 65, price_per_week: 390, price_per_month: 1495, store_id: 26 },
  { title: 'Lindgren Group', size: 419, price_per_day: 41, price_per_week: 246, price_per_month: 943, store_id: 20 },
  { title: 'Runte, Batz and Schuppe', size: 492, price_per_day: 49, price_per_week: 294, price_per_month: 1127, store_id: 16 },
  { title: 'Adams Inc', size: 995, price_per_day: 99, price_per_week: 594, price_per_month: 2277, store_id: 14 },
  { title: 'McDermott Group', size: 695, price_per_day: 69, price_per_week: 414, price_per_month: 1587, store_id: 10 },
  { title: 'Baumbach, Runolfsdottir and Hyatt', size: 881, price_per_day: 88, price_per_week: 528, price_per_month: 2024, store_id: 9 },
  { title: 'Lockman-Kertzmann', size: 123, price_per_day: 12, price_per_week: 72, price_per_month: 276, store_id: 28 },
  { title: 'Champlin-Ratke', size: 628, price_per_day: 62, price_per_week: 372, price_per_month: 1426, store_id: 10 },
  { title: 'Heathcote, Medhurst and Parker', size: 550, price_per_day: 55, price_per_week: 330, price_per_month: 1265, store_id: 6 },
  { title: 'Reilly LLC', size: 542, price_per_day: 54, price_per_week: 324, price_per_month: 1242, store_id: 16 },
  { title: 'Pollich Group', size: 351, price_per_day: 35, price_per_week: 210, price_per_month: 805, store_id: 13 },
  { title: 'Bode-Hayes', size: 342, price_per_day: 34, price_per_week: 204, price_per_month: 782, store_id: 25 },
  { title: 'Bergstrom, Blick and Hills', size: 643, price_per_day: 64, price_per_week: 384, price_per_month: 1472, store_id: 27 },
  { title: 'Wolff, Gleichner and Hodkiewicz', size: 102, price_per_day: 10, price_per_week: 60, price_per_month: 230, store_id: 9 },
  { title: 'Hermann, Herman and Sipes', size: 245, price_per_day: 24, price_per_week: 144, price_per_month: 552, store_id: 14 },
  { title: 'Legros, Kutch and Schroeder', size: 639, price_per_day: 63, price_per_week: 378, price_per_month: 1449, store_id: 3 },
  { title: 'Hand-Haley', size: 720, price_per_day: 72, price_per_week: 432, price_per_month: 1656, store_id: 15 },
  { title: 'Nicolas, Hackett and Conroy', size: 654, price_per_day: 65, price_per_week: 390, price_per_month: 1495, store_id: 5 },
  { title: 'Hessel-Yundt', size: 809, price_per_day: 80, price_per_week: 480, price_per_month: 1840, store_id: 27 },
  { title: 'Rolfson-Feil', size: 164, price_per_day: 16, price_per_week: 96, price_per_month: 368, store_id: 22 },
  { title: 'Daugherty and Sons', size: 141, price_per_day: 14, price_per_week: 84, price_per_month: 3, store_id: 2 }
]

stores_list.each do |store|
  Store.create(store)
end

spaces_list.each do |space|
  Space.create(space)
end
